apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: y9o398rqe-nodejs-gitops
  description: This is GitOps manifest for y9o398rqe-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=y9o398rqe-nodejs
    backstage.io/kubernetes-id: y9o398rqe-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: y9o398rqe-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:y9o398rqe-nodejs
