apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: y9o398rqe-nodejs
  janus-idp.io/tekton: y9o398rqe-nodejs
  backstage.io/kubernetes-id: y9o398rqe-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: y9o398rqe-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
