apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: y9o398rqe-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: y9o398rqe-nodejs 
  name: y9o398rqe-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: y9o398rqe-nodejs 
